{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\", job=\"prometheus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Space (Gb)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes) - sum(node_filesystem_free_bytes)) / 1000000000",
     "legendFormat": "Used Space"
    },
    {
     "expr": "(sum(node_filesystem_free_bytes)) / 1000000000",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_speed_bytes{device=\"eth0\", job=\"prometheus\"} / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}